yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('posts/<int:post_id>/like/',
         views.add_like,
         name='like'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .settings import LIMIT_STR_TEXT

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Идентификатор')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    DISPLAY = (
        '{text:.{LIMIT_STR_TEXT}}, '
        '{author}, '
        '{group}'
    )
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )
    likes = models.ManyToManyField(
        User,
        blank=True,
        related_name='likes',
        verbose_name='Лайк'
    )

    def __str__(self):
        return (self.DISPLAY.format(
            text=self.text,
            LIMIT_STR_TEXT=LIMIT_STR_TEXT,
            author=self.author.username,
            group=self.group
        ))

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    DISPLAY = (
        '{text:.{LIMIT_STR_TEXT}}, '
        '{author}'
    )
    text = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )

    def __str__(self):
        return (self.DISPLAY.format(
            text=self.text,
            LIMIT_STR_TEXT=LIMIT_STR_TEXT,
            author=self.author.username,
        ))

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': _('Введите текст поста'),
            'group': _('Выберите группу'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        help_texts = {
            'text': _('Напишите комент'),
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .settings import CACHE_IN_S, PAGINATOR_LIMIT


def get_page(request, list):
    return Paginator(list, PAGINATOR_LIMIT).get_page(
        request.GET.get('page')
    )


@cache_page(CACHE_IN_S, key_prefix='index_page')
def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': get_page(
            request,
            Post.objects.all()
        ),
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': get_page(request, group.posts.all()),
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    return render(request, 'posts/profile.html', {
        'author': author,
        'page_obj': get_page(request, author.posts.all()),
        'following':
            (request.user != author)
            and request.user.is_authenticated
            and Follow.objects.filter(
                user=request.user, author=author).exists()
    })


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'form': CommentForm()
    })


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form,
        })
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', {
        'post': post,
        'form': form,
    })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    return render(request, 'posts/follow.html', {
        'page_obj':
            get_page(request, Post.objects.filter(
                author__following__user=request.user)),
    })


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow.objects,
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username=username)


@login_required
def add_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    is_like = False
    for like in post.likes.all():
        if like == request.user:
            is_like = True
            break
    if not is_like:
        post.likes.add(request.user)
    if is_like:
        post.likes.remove(request.user)
    return redirect(request.POST.get('text'))

yatube/templates/posts/includes/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Комментировать:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in post.comments.all %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p><small class="text-muted">{{ comment.created|date:"d E Y" }}</small></p>
        <p>{{ comment.text|linebreaks }}</p>
        {% if not forloop.last %}<hr>{% endif %}
      </div>
    </div>
{% endfor %}

yatube/templates/posts/includes/like_comment.html
{% load static %}
<ul class="list-group list-group-horizontal">
  <li class="list-group-item">
    <form method="post" action="{% url 'posts:like' post.id %}">
      {% csrf_token %}
      <input type="hidden" name="text" value="{{ request.path }}">
      <button style="background: transparent; border: none; box-shadow: none;" type="submit">
        <img src="{% static 'img/heart.png' %}"
              class="img-fluid"
              width="20"
              height="20"
              alt="">
      </button>
    </form>
  </li>
  {% if post.likes.all.count > 0 %}
    <li class="list-group-item">
      {{ post.likes.all.count }}
    </li>
  {% endif %}
  <a href="{% url 'posts:post_detail' post.pk %}" class="list-group-item link-primary">
      Комментариев: {{ post.comments.count }}</a>
</ul>

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}
{# Отрисовываем навигацию паджинатора только если все посты не помещаются на первую страницу #}
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1"> << </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><</a>
        </li>
      {% endif %}
      {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">{{ page_num }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">></a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/includes/post.html
{% load thumbnail %}
<div class="card mb-4" style="width: {{post_width}};">
  <div class="card-body">
    <h5 class="card-title">
      Автор: <a href="{% url 'posts:profile' post.author.username %}">
        {{ post.author.get_full_name }}</a>
    </h5>
    <p class="card-text"><small class="text-muted">{{ post.pub_date|date:"d E Y" }}</small></p>
    {% thumbnail post.image "1280x720" crop="center" padding=True upscale=True as im %}
      <img class="img-fluid rounded-start" src="{{ im.url }}" alt="Card image cap">
    {% endthumbnail %}
    <p class="card-text">{{ post.text|linebreaks }}</p>
    {% if post.group and not no_display_group %}
      <a href="{% url 'posts:group_list' post.group.slug %}" class="card-link">#{{ post.group.title }}</a>
    {% endif %}
    <p>{% include "posts/includes/like_comment.html" %}</p>
  </div>
  {% if user == post.author %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'posts:post_edit' post.pk %}" role="button">
          Редактировать
        </a>
    {% endif %}
</div>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}