yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('posts/<int:post_id>/like/',
         views.add_like,
         name='like'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .settings import LIMIT_STR_TEXT

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Идентификатор')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    DISPLAY = (
        '{text:.{LIMIT_STR_TEXT}}, '
        '{author}, '
        '{group}'
    )
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )
    likes = models.ManyToManyField(
        User,
        blank=True,
        related_name='likes',
        verbose_name='Лайк'
    )

    def __str__(self):
        return (self.DISPLAY.format(
            text=self.text,
            LIMIT_STR_TEXT=LIMIT_STR_TEXT,
            author=self.author.username,
            group=self.group
        ))

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    DISPLAY = (
        '{text:.{LIMIT_STR_TEXT}}, '
        '{author}'
    )
    text = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )

    def __str__(self):
        return (self.DISPLAY.format(
            text=self.text,
            LIMIT_STR_TEXT=LIMIT_STR_TEXT,
            author=self.author.username,
        ))

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': _('Введите текст поста'),
            'group': _('Выберите группу'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        help_texts = {
            'text': _('Напишите комент'),
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .settings import CACHE_IN_S, PAGINATOR_LIMIT


def get_page(request, list):
    return Paginator(list, PAGINATOR_LIMIT).get_page(
        request.GET.get('page')
    )


@cache_page(CACHE_IN_S, key_prefix='index_page')
def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': get_page(
            request,
            Post.objects.all()
        ),
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': get_page(request, group.posts.all()),
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    return render(request, 'posts/profile.html', {
        'author': author,
        'page_obj': get_page(request, author.posts.all()),
        'following':
            (request.user != author)
            and request.user.is_authenticated
            and Follow.objects.filter(
                user=request.user, author=author).exists()
    })


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'form': CommentForm()
    })


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form,
        })
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', {
        'post': post,
        'form': form,
    })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    return render(request, 'posts/follow.html', {
        'page_obj':
            get_page(request, Post.objects.filter(
                author__following__user=request.user)),
    })


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow.objects,
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username=username)


@login_required
def add_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    is_like = False
    for like in post.likes.all():
        if like == request.user:
            is_like = True
            break
    if not is_like:
        post.likes.add(request.user)
    if is_like:
        post.likes.remove(request.user)
    return redirect(request.POST.get('text'))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if post %}Редактировать запись{% else %}Добавить запись{% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if post %}Редактировать запись{% else %}Добавить запись{% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
              <form method="post" enctype="multipart/form-data" action=
                {% if post %}
                  "{% url 'posts:post_edit' post.pk %}"
                {% else %}
                  "{% url 'posts:post_create' %}"
                {% endif %}>{% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                    </label>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                    {% endif %}
                  </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if post %}Сохранить{% else %}Добавить{% endif %}
                  </button>
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Избранное{% endblock title %}
{% block content %}
  {% load thumbnail %}
  <div class="container">
    <h1>Избранное</h1>
    {% include 'posts/includes/switcher.html' with follow=True %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' %}
      {% if not forloop.last %}<p>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{ group.title }} {% endblock title %}
{% block content %}
  {% load thumbnail %}
  <div class="container">
    <figure class="text-center">
      <h1>{{ group.title }}</h1>
      <p><em>{{ group.description|linebreaksbr }}</em></p>
    </figure>
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' with no_display_group=True post_width=68rem %}
        {% if not forloop.last %}<p>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock title %}
{% block content %}
  {% load thumbnail %}
  <p></p>
  <main class="container">
    {% if page_obj.number == 1%}
      <div class="p-5 p-md-5 mb-4 text-white rounded bg-secondary">
        <div class="col-md-10 px-0">
          <h1 class="display-4 fst-italic">Привет, гость!</h1>
          <p class="lead my-3"><em>Этот блог создан в рамках учебного курса 
            <a href="https://practicum.yandex.ru" class="link-dark" target="_blank">"Яндекс Практикум"</a>
            и самостоятельных потуг </em> <span>&#x1F609</span>
          </p>
          <p class="lead my-3"><em>Здесь вы можете регистрироваться, писать посты,
            подписываться на других пользовотелей, оставлять коменты и ставить лукасы.</em>
          </p>
          <p class="lead my-3"><em>Функционал будет постепенно расширяться </em><span>😈</span>
          </p>
        </div>
      </div>
    {% endif %}
  <div class="container">
    <figure class="text-center">
      <h1>Последние обновления на сайте</h1>
    </figure>
    {% include 'posts/includes/switcher.html' with index=True %}
    {% for post in page_obj %}
      {% include 'posts/includes/post.html' with post_width=68rem %}
      {% if not forloop.last %}<p>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock title %}
{% block content %}
  {% load thumbnail %}
  <main class="container">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              {{ post.author.get_full_name }}</a></li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          {% if post.group %}
            <li class="list-group-item">
              <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group.title }}</a>
            </li>
          {% endif %}
          {% if user == post.author %}
          <a class="btn btn-sm btn-secondary" href="{% url 'posts:post_edit' post.pk %}" role="button">
            Редактировать
          </a>
          {% endif %}
        </ul>
      </aside>
      <article class="col-12 col-md-8">
        {% thumbnail post.image "1280x720" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaks }}</p>
        {% if not forloop.last %}<hr>{% endif %}
        {% include "posts/includes/like_comment.html" %}   
        <p>{% include "posts/includes/comments.html" with comments=comments %}</p>
      </article>
    </div>
  </main>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }} {% endblock title %}
{% block content %}
  {% load thumbnail %}
    <div class="row g-5">
      <div class="col-md-3">
        <div class="position-sticky" style="top: 1rem;">
          <div class="p-4 mb-9">
            <ul class="list-group">
              <li class="list-group-item active" aria-current="true">
                {{ author.get_full_name }}
              </li>
              <li class="list-group-item">Постов: {{ author.posts.count }}</li>
              <li class="list-group-item">Комментариев: {{ author.comments.count }}</li>
              <li class="list-group-item">Подписок: {{ author.follower.count }}</li>
              <li class="list-group-item">Подписано: {{ author.following.count }}</li>
              {% if user != author and user.is_authenticated %}
                {% if following %}
                  <a class="btn btn-outline-danger"
                      href="{% url 'posts:profile_unfollow' author.username %}" 
                      role="button">Отписаться</a> 
                {% else %}
                  <a class="btn btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}" role="button">
                    Подписаться</a>
                {% endif %}
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <figure class="text-center">
          <p><h3>{{ author.get_full_name }} все посты</h3></p>
        </figure>
        {% for post in page_obj %}
          {% include 'posts/includes/post.html' with post_width=50rem %}
          {% if not forloop.last %}<p>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>

    </div>
  </div>
{% endblock content %}